version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: tamagotchi
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tamagotchi
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci

    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
